name: Epic Hokkaido
favicon: null
layout_spectrum: 0.5883166096173227
typography_spectrum: 0.3038588815834373
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5461044253315777
  lightness: 0.20893539232201874
  saturation: 0.03805589000694454
  rhythmicContrast: 0.1967066628858447
purpose: []
