name: Epic Hokkaido
favicon: null
layout_spectrum: 0.5883166096173227
typography_spectrum: 0.3038588815834373
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#000000'
    - '#000000'
    - '#000000'
    - '#000000'
  brandStrength: 0.375
  lightness: 0
  saturation: 0.6875
  rhythmicContrast: 0
purpose: []
